/**
 * Post-processing script for generated Supabase types
 * Makes the file more readable for Claude and developers
 */

const fs = require('fs');
const path = require('path');

const TYPES_FILE = path.join(__dirname, '..', 'types', 'database.types.ts');

function formatTypes() {
  if (!fs.existsSync(TYPES_FILE)) {
    console.log('⚠️  No types file found, skipping formatting');
    return;
  }

  let content = fs.readFileSync(TYPES_FILE, 'utf8');

  // Add header comment
  const header = `/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * 
 * Generated by: eryai-core-schema
 * Source: Supabase project tjqxseptmeypfsymrrln
 * Generated at: ${new Date().toISOString()}
 * 
 * This file is automatically synced to all EryAI spoke-repos.
 * To update, modify the database schema in Supabase and run
 * the "Broadcast Schema" workflow in eryai-core-schema.
 */

`;

  // Check if header already exists
  if (!content.startsWith('/**')) {
    content = header + content;
  }

  // Write formatted content
  fs.writeFileSync(TYPES_FILE, content);
  console.log('✅ Types file formatted successfully');
}

formatTypes();
